version: '3'
services:
  api-test:
    container_name: api-test
    build:
      dockerfile: Dockerfile
      context: .
    command:
      bash -c "npm run test-failure"
    environment:
      - PORT=5000
      - ATLAS_URI=${ATLAS_URI}
      - DEV_URI=${DEV_URI}
      - NODE_ENV=development
      - API_HOST=${API_HOST}
      - API_PORT=443
      - DEV_API_HOST=http://127.0.0.1
      - DEV_API_PORT=5000
      - CLIENT_HOST=${CLIENT_HOST}
      - CLIENT_PORT=443
      - DEV_CLIENT_HOST=http://127.0.0.1
      - DEV_CLIENT_PORT=3000
    ports:
      - '5000:5000'
