
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Backend with CucumberJs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: backend

jobs:
  build:

    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        #Secret Secret Shh
    env: 
      API_HOST: ${{ secrets.API_HOST}}
      ATLAS_URI: ${{ secrets.ATLAS_URI }}
      CLIENT_HOST: ${{ secrets.CLIENT_HOST }}
      DEV_URI: ${{ secrets.DEV_URI }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        
    steps:
    - uses: actions/checkout@v2
    
# something seems to be breaking because of the caching
    - run: mkdir -p /home/runner/.npm 
      continue-on-error: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Build Docker
      run: docker-compose -f 'docker-compose.test.yml' -p pour-decisions-api-testing up -d 

    - name: Run test
      run: docker-compose -f 'docker-compose.test.yml' -p pour-decisions-api-testing up --build --exit-code-from api-test

