# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Heroku

on:
  workflow_run:
    workflows: ['Test Frontend React App', 'Test Backend with CucumberJs']
    branches: [main]
    types: [completed]

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-workflow-run-wait@v1
    - name: Deploy backend # might not need to separate since we only have 1 server
      uses: akhileshns/heroku-deploy@v3.12.12   
      with:
        heroku_api_key: 'eec413be-8238-4e52-a1b5-d61505002bb6'
        heroku_app_name: 'pour-decisions-app'
        heroku_email: 'minh-tuan.chau@mail.mcgill.ca'
        appdir: 'backend' 
    - name: Deploy Frontend
      uses: akhileshns/heroku-deploy@v3.12.12  
      with:
        heroku_api_key: '6c6171f4-6dd1-49c7-bc0d-d25a94f39eee'
        heroku_app_name: 'pour-decisions-app'
        heroku_email: 'minh-tuan.chau@mail.mcgill.ca'
        appdir: 'frontend'  

